#!/bin/bash

SOURCE_DIR="${1:-/var/www/html}"
BACKUP_DIR="${2:-/var/backups}"

date=$(date +'%Y-%m-%d_%H-%M-%S')
mkdir -p "$BACKUP_DIR"
tar -czf "$BACKUP_DIR/backup_${date}.tar.gz" $SOURCE_DIR 2>/dev/null

find "$BACKUP_DIR" -type f -name backup_*.tar.gz -mtime +7 -delete


