#!/bin/bash

RED='\033[0;31m'
GREEN='\033[0;32m'
RESET='\033[0m'

disk_usage=$(df -h |grep /dev/sda3 | awk '{print $5}'| tr -d "%")
over_usage=$(ps -eo pid,ppid,cmd,%mem,%cpu --sort=-%mem | head -n 6)	

if (( "$disk_usage" >= 1 )); then
	echo -e "${RED}[MEMORY USAGE: $disk_usage]\nMost MEMORY usage Proccesses:\n ${RESET}$over_usage"
	curl -d "AAAAAAAAAAHHHHHHHHHHHHH MEMORY USAGE: $disk_usage" ntfy.sh/YOUR_NTFY_URL_HERE
fi
