#!/bin/bash

services=("${@:-sshd crond docker}")

monitor_service(){
	local service_name="$1"
	if systemctl is-active --quiet "$service_name"; then
		return 0
	else
		return 1
	fi
}


for service in ${services[@]}; do

	if monitor_service "$service"; then 
		echo "[OK] The service "$service" is UP"
	else
		echo "[ALERT] The service "$service" is DOWN"
	fi
done
